sample1: sample1.cpp
	g++ -o sample1 sample1.cpp -lpthread
sample2: sample2.cpp
	g++ -o sample2 sample2.cpp -lpthread
semdemo: semdemo.cpp
	g++ -o semdemo semdemo.cpp -lpthread
seminit: seminit.cpp
	g++ -o seminit seminit.cpp -lpthread
sample: sample.cpp
	g++ -o sample sample.cpp -lpthread
all: sample sample1 sample2 semdemo seminit
clean: rm sample sample1 sample2 seminit semdemo
